FROM node:18-alpine3.17 as build
WORKDIR /usr/src/bot
COPY package*.json ./

RUN npm install
RUN npm i -g tsc-watch

COPY ./src ./
COPY ./tsconfig.json ./

ENV BOT_ENV=dev
CMD tsc-watch --onSuccess "npm run start-build"
